version: '3.9'

services:

  rabbitmq:
    container_name: devrabbitmq
    # restart: always
    image: rabbitmq:3.10-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=supersenha
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./tmp_data/rabbitmq_data:/var/lib/rabbitmq
